services:
  - type: web
    name: cquizy-api
    env: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: cquizy-mongodb
          property: connectionString
      - key: PORT
        value: 10000
